# Pandas - Works in Structured data

In [1]:
import pandas as pd
pd.__version__

'3.0.1'

In [2]:
# Dataframe

df = pd.DataFrame([11,22,33],columns=["Column"])
print(df)
print(type(df))

   Column
0      11
1      22
2      33
<class 'pandas.DataFrame'>

In [3]:
data = {
    'name': ['Madan','Shyam','Suman','Yama','Zoya'],
    'rollno.' : [1,2,3,4,5],
    'percentage(%)': [89,90,67,81,92]
}

df = pd.DataFrame(data)
df

    name  rollno.  percentage(%)
0  Madan        1             89
1  Shyam        2             90
2  Suman        3             67
3   Yama        4             81
4   Zoya        5             92

In [6]:
# Dataframe understanding

In [7]:
df.head(2)

    name  rollno.  percentage(%)
0  Madan        1             89
1  Shyam        2             90

In [8]:
df.tail(3)

    name  rollno.  percentage(%)
2  Suman        3             67
3   Yama        4             81
4   Zoya        5             92

In [9]:
df.shape

(5, 3)

In [10]:
df.columns

Index(['name', 'rollno.', 'percentage(%)'], dtype='str')

In [11]:
df.rename(columns= {"rollno.": 'roll_no'})

    name  roll_no  percentage(%)
0  Madan        1             89
1  Shyam        2             90
2  Suman        3             67
3   Yama        4             81
4   Zoya        5             92

In [12]:
df        # no change in DATAFRAME

    name  rollno.  percentage(%)
0  Madan        1             89
1  Shyam        2             90
2  Suman        3             67
3   Yama        4             81
4   Zoya        5             92

In [13]:
df.rename(columns= {"rollno.": 'roll_no'},inplace = True)
df

    name  roll_no  percentage(%)
0  Madan        1             89
1  Shyam        2             90
2  Suman        3             67
3   Yama        4             81
4   Zoya        5             92

In [14]:
df       # Change

    name  roll_no  percentage(%)
0  Madan        1             89
1  Shyam        2             90
2  Suman        3             67
3   Yama        4             81
4   Zoya        5             92

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           5 non-null      str
 1   roll_no        5 non-null      int64
 2   percentage(%)  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [16]:
df.describe()

        roll_no  percentage(%)
count  5.000000       5.000000
mean   3.000000      83.800000
std    1.581139      10.281051
min    1.000000      67.000000
25%    2.000000      81.000000
50%    3.000000      89.000000
75%    4.000000      90.000000
max    5.000000      92.000000

In [17]:
# Save and Load data in csv [csv- Comma-Separated Values]

In [18]:
df.to_csv("Student.csv",index = False) # export

In [19]:
load_df = pd.read_csv("Student.csv") # import
load_df

    name  roll_no  percentage(%)
0  Madan        1             89
1  Shyam        2             90
2  Suman        3             67
3   Yama        4             81
4   Zoya        5             92

In [20]:
# Rows and columns selection
# columns selection
df[['name']] #single column
df[['name','roll_no']] #2 column

    name  roll_no
0  Madan        1
1  Shyam        2
2  Suman        3
3   Yama        4
4   Zoya        5

In [21]:
# select rows
# loc - label based index
df.loc[df.name=="Madan"]
df.loc[(df.name=='Madan')& (df['percentage(%)']>80)]

    name  roll_no  percentage(%)
0  Madan        1             89

In [22]:
# iloc - index-value based
df.iloc[0]
df.iloc[0:6] # Gives full data 
# [start:stop:step]
df.iloc[1:6:3]

    name  roll_no  percentage(%)
1  Shyam        2             90
4   Zoya        5             92

In [23]:
# Filter dataframe
df['percentage(%)']>85
# not true or false we want the exact info for this we use
df[df['percentage(%)']>85]

    name  roll_no  percentage(%)
0  Madan        1             89
1  Shyam        2             90
4   Zoya        5             92

In [24]:
# for two conditions we have to 
df[(df['percentage(%)'] >= 80)&(df['roll_no'] < 6)]

    name  roll_no  percentage(%)
0  Madan        1             89
1  Shyam        2             90
3   Yama        4             81
4   Zoya        5             92

In [28]:
import pandas as pd
import io
Data = """James Smith,29,1,3071498
Maria Garcia,37,8,4339738
Robert Johnson,28,6,4476605
Maria Rodriguez,27,5,4101196
David Smith,24,1,2824905
Mary Hernandez,35,4,4007157
Michael Williams,60,2,3668185
James Brown,34,12,5721024
Patricia Martinez,48,8,4760797
Jennifer Miller,59,18,6233798
Linda Davis,32,7,4405142
Barbara Wilson,39,5,3820241
Elizabeth Moore,43,4,3446077
Richard Taylor,46,4,3808123
Thomas Anderson,44,20,6999639
Joseph Thomas,24,3,3737241
Charles Jackson,56,8,4664683
Christopher White,27,5,3926149
Daniel Harris,45,19,6693950
Matthew Martin,26,1,3007339
Anthony Thompson,40,3,3429062
Donald Young,28,4,3697982
Mark King,51,21,7343591
Paul Wright,32,6,4218060
Steven Lopez,35,11,5135542
Andrew Scott,26,5,3760149
Kenneth Green,56,16,6032191
Joshua Adams,51,13,5554526
Kevin Baker,57,15,6043479
Brian Gonzalez,25,2,2948575"""

columns = ["Employee Name","Age" ,"Experience","Min Salary"]
df = pd.read_csv(io.StringIO(Data),names = columns)
df

        Employee Name  Age  Experience  Min Salary
0         James Smith   29           1     3071498
1        Maria Garcia   37           8     4339738
2      Robert Johnson   28           6     4476605
3     Maria Rodriguez   27           5     4101196
4         David Smith   24           1     2824905
5      Mary Hernandez   35           4     4007157
6    Michael Williams   60           2     3668185
7         James Brown   34          12     5721024
8   Patricia Martinez   48           8     4760797
9     Jennifer Miller   59          18     6233798
10        Linda Davis   32           7     4405142
11     Barbara Wilson   39           5     3820241
12    Elizabeth Moore   43           4     3446077
13     Richard Taylor   46           4     3808123
14    Thomas Anderson   44          20     6999639
15      Joseph Thomas   24           3     3737241
16    Charles Jackson   56           8     4664683
17  Christopher White   27           5     3926149
18      Daniel Harris   45          19     6693950
19     Matthew Martin   26           1     3007339
20   Anthony Thompson   40           3     3429062
21       Donald Young   28           4     3697982
22          Mark King   51          21     7343591
23        Paul Wright   32           6     4218060
24       Steven Lopez   35          11     5135542
25       Andrew Scott   26           5     3760149
26      Kenneth Green   56          16     6032191
27       Joshua Adams   51          13     5554526
28        Kevin Baker   57          15     6043479
29     Brian Gonzalez   25           2     2948575

In [31]:
!pip install openpyxl
file_name = "my_analysis.xlsx"
df.to_excel(file_name, index=False) 
df

Requirement already satisfied: openpyxl in C:\Users\welcome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\welcome\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)

        Employee Name  Age  Experience  Min Salary
0         James Smith   29           1     3071498
1        Maria Garcia   37           8     4339738
2      Robert Johnson   28           6     4476605
3     Maria Rodriguez   27           5     4101196
4         David Smith   24           1     2824905
5      Mary Hernandez   35           4     4007157
6    Michael Williams   60           2     3668185
7         James Brown   34          12     5721024
8   Patricia Martinez   48           8     4760797
9     Jennifer Miller   59          18     6233798
10        Linda Davis   32           7     4405142
11     Barbara Wilson   39           5     3820241
12    Elizabeth Moore   43           4     3446077
13     Richard Taylor   46           4     3808123
14    Thomas Anderson   44          20     6999639
15      Joseph Thomas   24           3     3737241
16    Charles Jackson   56           8     4664683
17  Christopher White   27           5     3926149
18      Daniel Harris   45          19     6693950
19     Matthew Martin   26           1     3007339
20   Anthony Thompson   40           3     3429062
21       Donald Young   28           4     3697982
22          Mark King   51          21     7343591
23        Paul Wright   32           6     4218060
24       Steven Lopez   35          11     5135542
25       Andrew Scott   26           5     3760149
26      Kenneth Green   56          16     6032191
27       Joshua Adams   51          13     5554526
28        Kevin Baker   57          15     6043479
29     Brian Gonzalez   25           2     2948575

In [24]:
df[(df['Min Salary'] > 5000000 )&(df['Experience']>10)]

      Employee Name  Age  Experience  Min Salary
7       James Brown   34          12     5721024
9   Jennifer Miller   59          18     6233798
14  Thomas Anderson   44          20     6999639
18    Daniel Harris   45          19     6693950
22        Mark King   51          21     7343591
24     Steven Lopez   35          11     5135542
26    Kenneth Green   56          16     6032191
27     Joshua Adams   51          13     5554526
28      Kevin Baker   57          15     6043479

In [25]:
df[(df['Min Salary'] >2500000) & (df['Experience']<10)]

        Employee Name  Age  Experience  Min Salary
0         James Smith   29           1     3071498
1        Maria Garcia   37           8     4339738
2      Robert Johnson   28           6     4476605
3     Maria Rodriguez   27           5     4101196
4         David Smith   24           1     2824905
5      Mary Hernandez   35           4     4007157
6    Michael Williams   60           2     3668185
8   Patricia Martinez   48           8     4760797
10        Linda Davis   32           7     4405142
11     Barbara Wilson   39           5     3820241
12    Elizabeth Moore   43           4     3446077
13     Richard Taylor   46           4     3808123
15      Joseph Thomas   24           3     3737241
16    Charles Jackson   56           8     4664683
17  Christopher White   27           5     3926149
19     Matthew Martin   26           1     3007339
20   Anthony Thompson   40           3     3429062
21       Donald Young   28           4     3697982
23        Paul Wright   32           6     4218060
25       Andrew Scott   26           5     3760149
29     Brian Gonzalez   25           2     2948575

In [26]:
df.where(df['Age'] >= 30)

        Employee Name   Age  Experience  Min Salary
0                 NaN   NaN         NaN         NaN
1        Maria Garcia  37.0         8.0   4339738.0
2                 NaN   NaN         NaN         NaN
3                 NaN   NaN         NaN         NaN
4                 NaN   NaN         NaN         NaN
5      Mary Hernandez  35.0         4.0   4007157.0
6    Michael Williams  60.0         2.0   3668185.0
7         James Brown  34.0        12.0   5721024.0
8   Patricia Martinez  48.0         8.0   4760797.0
9     Jennifer Miller  59.0        18.0   6233798.0
10        Linda Davis  32.0         7.0   4405142.0
11     Barbara Wilson  39.0         5.0   3820241.0
12    Elizabeth Moore  43.0         4.0   3446077.0
13     Richard Taylor  46.0         4.0   3808123.0
14    Thomas Anderson  44.0        20.0   6999639.0
15                NaN   NaN         NaN         NaN
16    Charles Jackson  56.0         8.0   4664683.0
17                NaN   NaN         NaN         NaN
18      Daniel Harris  45.0        19.0   6693950.0
19                NaN   NaN         NaN         NaN
20   Anthony Thompson  40.0         3.0   3429062.0
21                NaN   NaN         NaN         NaN
22          Mark King  51.0        21.0   7343591.0
23        Paul Wright  32.0         6.0   4218060.0
24       Steven Lopez  35.0        11.0   5135542.0
25                NaN   NaN         NaN         NaN
26      Kenneth Green  56.0        16.0   6032191.0
27       Joshua Adams  51.0        13.0   5554526.0
28        Kevin Baker  57.0        15.0   6043479.0
29                NaN   NaN         NaN         NaN

In [27]:
df.where(df['Age'] >= 30, other = 'Not available')

        Employee Name            Age     Experience     Min Salary
0       Not available  Not available  Not available  Not available
1        Maria Garcia             37              8        4339738
2       Not available  Not available  Not available  Not available
3       Not available  Not available  Not available  Not available
4       Not available  Not available  Not available  Not available
5      Mary Hernandez             35              4        4007157
6    Michael Williams             60              2        3668185
7         James Brown             34             12        5721024
8   Patricia Martinez             48              8        4760797
9     Jennifer Miller             59             18        6233798
10        Linda Davis             32              7        4405142
11     Barbara Wilson             39              5        3820241
12    Elizabeth Moore             43              4        3446077
13     Richard Taylor             46              4        3808123
14    Thomas Anderson             44             20        6999639
15      Not available  Not available  Not available  Not available
16    Charles Jackson             56              8        4664683
17      Not available  Not available  Not available  Not available
18      Daniel Harris             45             19        6693950
19      Not available  Not available  Not available  Not available
20   Anthony Thompson             40              3        3429062
21      Not available  Not available  Not available  Not available
22          Mark King             51             21        7343591
23        Paul Wright             32              6        4218060
24       Steven Lopez             35             11        5135542
25      Not available  Not available  Not available  Not available
26      Kenneth Green             56             16        6032191
27       Joshua Adams             51             13        5554526
28        Kevin Baker             57             15        6043479
29      Not available  Not available  Not available  Not available

In [28]:
# Rows and column -- operations(add,subtract,multiple,division)
df

        Employee Name  Age  Experience  Min Salary
0         James Smith   29           1     3071498
1        Maria Garcia   37           8     4339738
2      Robert Johnson   28           6     4476605
3     Maria Rodriguez   27           5     4101196
4         David Smith   24           1     2824905
5      Mary Hernandez   35           4     4007157
6    Michael Williams   60           2     3668185
7         James Brown   34          12     5721024
8   Patricia Martinez   48           8     4760797
9     Jennifer Miller   59          18     6233798
10        Linda Davis   32           7     4405142
11     Barbara Wilson   39           5     3820241
12    Elizabeth Moore   43           4     3446077
13     Richard Taylor   46           4     3808123
14    Thomas Anderson   44          20     6999639
15      Joseph Thomas   24           3     3737241
16    Charles Jackson   56           8     4664683
17  Christopher White   27           5     3926149
18      Daniel Harris   45          19     6693950
19     Matthew Martin   26           1     3007339
20   Anthony Thompson   40           3     3429062
21       Donald Young   28           4     3697982
22          Mark King   51          21     7343591
23        Paul Wright   32           6     4218060
24       Steven Lopez   35          11     5135542
25       Andrew Scott   26           5     3760149
26      Kenneth Green   56          16     6032191
27       Joshua Adams   51          13     5554526
28        Kevin Baker   57          15     6043479
29     Brian Gonzalez   25           2     2948575

In [29]:
# Add new column 
import pandas as pd
import io
Data = """James Smith,29,1,3071498
Maria Garcia,37,8,4339738
Robert Johnson,28,6,4476605
Maria Rodriguez,27,5,4101196
David Smith,24,1,2824905
Mary Hernandez,35,4,4007157
Michael Williams,60,2,3668185
James Brown,34,12,5721024
Patricia Martinez,48,8,4760797
Jennifer Miller,59,18,6233798
Linda Davis,32,7,4405142
Barbara Wilson,39,5,3820241
Elizabeth Moore,43,4,3446077
Richard Taylor,46,4,3808123
Thomas Anderson,44,20,6999639
Joseph Thomas,24,3,3737241
Charles Jackson,56,8,4664683
Christopher White,27,5,3926149
Daniel Harris,45,19,6693950
Matthew Martin,26,1,3007339
Anthony Thompson,40,3,3429062
Donald Young,28,4,3697982
Mark King,51,21,7343591
Paul Wright,32,6,4218060
Steven Lopez,35,11,5135542
Andrew Scott,26,5,3760149
Kenneth Green,56,16,6032191
Joshua Adams,51,13,5554526
Kevin Baker,57,15,6043479
Brian Gonzalez,25,2,2948575"""

columns = ["Employee_Name","Age" ,"Experience","Min Salary"]
df = pd.read_csv(io.StringIO(Data),names = columns)
df

df['categories'] = ["Entry-Level", "Mid-Level", "Mid-Level", "Mid-Level", "Entry-Level", 
    "Mid-Level", "Mid-Level", "Senior Management", "Senior Management", "Executive", 
    "Mid-Level", "Mid-Level", "Entry-Level", "Mid-Level", "Executive", 
    "Mid-Level", "Senior Management", "Mid-Level", "Executive", "Entry-Level", 
    "Entry-Level", "Mid-Level", "Executive", "Mid-Level", "Senior Management", 
    "Mid-Level", "Executive", "Senior Management", "Executive", "Entry-Level"]
df

        Employee_Name  Age  Experience  Min Salary         categories
0         James Smith   29           1     3071498        Entry-Level
1        Maria Garcia   37           8     4339738          Mid-Level
2      Robert Johnson   28           6     4476605          Mid-Level
3     Maria Rodriguez   27           5     4101196          Mid-Level
4         David Smith   24           1     2824905        Entry-Level
5      Mary Hernandez   35           4     4007157          Mid-Level
6    Michael Williams   60           2     3668185          Mid-Level
7         James Brown   34          12     5721024  Senior Management
8   Patricia Martinez   48           8     4760797  Senior Management
9     Jennifer Miller   59          18     6233798          Executive
10        Linda Davis   32           7     4405142          Mid-Level
11     Barbara Wilson   39           5     3820241          Mid-Level
12    Elizabeth Moore   43           4     3446077        Entry-Level
13     Richard Taylor   46           4     3808123          Mid-Level
14    Thomas Anderson   44          20     6999639          Executive
15      Joseph Thomas   24           3     3737241          Mid-Level
16    Charles Jackson   56           8     4664683  Senior Management
17  Christopher White   27           5     3926149          Mid-Level
18      Daniel Harris   45          19     6693950          Executive
19     Matthew Martin   26           1     3007339        Entry-Level
20   Anthony Thompson   40           3     3429062        Entry-Level
21       Donald Young   28           4     3697982          Mid-Level
22          Mark King   51          21     7343591          Executive
23        Paul Wright   32           6     4218060          Mid-Level
24       Steven Lopez   35          11     5135542  Senior Management
25       Andrew Scott   26           5     3760149          Mid-Level
26      Kenneth Green   56          16     6032191          Executive
27       Joshua Adams   51          13     5554526  Senior Management
28        Kevin Baker   57          15     6043479          Executive
29     Brian Gonzalez   25           2     2948575        Entry-Level

In [30]:
df['Bonus']= df['Min Salary']*0.2
df
# add a new column
df.loc[len(df)] = {
    df.columns[0]:'Rishab',
    df.columns[1]: 26,
    df.columns[2]:1,
    df.columns[3]:8800000,
    df.columns[4]:'Entry-level',
    df.columns[5]:8800000,
}
df = df.drop_duplicates(subset=['Employee_Name'], keep='first')
df

,Employee_Name,Age,Experience,Min Salary,categories,Bonus
0,James Smith,29,1,3071498,Entry-Level,614299.6
1,Maria Garcia,37,8,4339738,Mid-Level,867947.6
2,Robert Johnson,28,6,4476605,Mid-Level,895321.0
3,Maria Rodriguez,27,5,4101196,Mid-Level,820239.2
4,David Smith,24,1,2824905,Entry-Level,564981.0
5,Mary Hernandez,35,4,4007157,Mid-Level,801431.4
6,Michael Williams,60,2,3668185,Mid-Level,733637.0
7,James Brown,34,12,5721024,Senior Management,1144204.8
8,Patricia Martinez,48,8,4760797,Senior Management,952159.4
9,Jennifer Miller,59,18,6233798,Executive,1246759.6
10,Linda Davis,32,7,4405142,Mid-Level,881028.4
11,Barbara Wilson,39,5,3820241,Mid-Level,764048.2
12,Elizabeth Moore,43,4,3446077,Entry-Level,689215.4
13,Richard Taylor,46,4,3808123,Mid-Level,761624.6
14,Thomas Anderson,44,20,6999639,Executive,1399927.8
15,Joseph Thomas,24,3,3737241,Mid-Level,747448.2
16,Charles Jackson,56,8,4664683,Senior Management,932936.6
17,Christopher White,27,5,3926149,Mid-Level,785229.8
18,Daniel Harris,45,19,6693950,Executive,1338790.0
19,Matthew Martin,26,1,3007339,Entry-Level,601467.8
20,Anthony Thompson,40,3,3429062,Entry-Level,685812.4
21,Donald Young,28,4,3697982,Mid-Level,739596.4
22,Mark King,51,21,7343591,Executive,1468718.2
23,Paul Wright,32,6,4218060,Mid-Level,843612.0
24,Steven Lopez,35,11,5135542,Senior Management,1027108.4
25,Andrew Scott,26,5,3760149,Mid-Level,752029.8
26,Kenneth Green,56,16,6032191,Executive,1206438.2
27,Joshua Adams,51,13,5554526,Senior Management,1110905.2
28,Kevin Baker,57,15,6043479,Executive,1208695.8
29,Brian Gonzalez,25,2,2948575,Entry-Level,589715.0
30,Rishab,26,1,8800000,Entry-level,8800000.0

In [31]:
len(df)

31

In [32]:
# update 
df.loc[0,'Min Salary'] = 3170000
df

,Employee_Name,Age,Experience,Min Salary,categories,Bonus
0,James Smith,29,1,3170000,Entry-Level,614299.6
1,Maria Garcia,37,8,4339738,Mid-Level,867947.6
2,Robert Johnson,28,6,4476605,Mid-Level,895321.0
3,Maria Rodriguez,27,5,4101196,Mid-Level,820239.2
4,David Smith,24,1,2824905,Entry-Level,564981.0
5,Mary Hernandez,35,4,4007157,Mid-Level,801431.4
6,Michael Williams,60,2,3668185,Mid-Level,733637.0
7,James Brown,34,12,5721024,Senior Management,1144204.8
8,Patricia Martinez,48,8,4760797,Senior Management,952159.4
9,Jennifer Miller,59,18,6233798,Executive,1246759.6
10,Linda Davis,32,7,4405142,Mid-Level,881028.4
11,Barbara Wilson,39,5,3820241,Mid-Level,764048.2
12,Elizabeth Moore,43,4,3446077,Entry-Level,689215.4
13,Richard Taylor,46,4,3808123,Mid-Level,761624.6
14,Thomas Anderson,44,20,6999639,Executive,1399927.8
15,Joseph Thomas,24,3,3737241,Mid-Level,747448.2
16,Charles Jackson,56,8,4664683,Senior Management,932936.6
17,Christopher White,27,5,3926149,Mid-Level,785229.8
18,Daniel Harris,45,19,6693950,Executive,1338790.0
19,Matthew Martin,26,1,3007339,Entry-Level,601467.8
20,Anthony Thompson,40,3,3429062,Entry-Level,685812.4
21,Donald Young,28,4,3697982,Mid-Level,739596.4
22,Mark King,51,21,7343591,Executive,1468718.2
23,Paul Wright,32,6,4218060,Mid-Level,843612.0
24,Steven Lopez,35,11,5135542,Senior Management,1027108.4
25,Andrew Scott,26,5,3760149,Mid-Level,752029.8
26,Kenneth Green,56,16,6032191,Executive,1206438.2
27,Joshua Adams,51,13,5554526,Senior Management,1110905.2
28,Kevin Baker,57,15,6043479,Executive,1208695.8
29,Brian Gonzalez,25,2,2948575,Entry-Level,589715.0
30,Rishab,26,1,8800000,Entry-level,8800000.0

In [33]:
# updated value
df.loc[df.Employee_Name =='Rishab','Min Salary'] = 9500000
df

,Employee_Name,Age,Experience,Min Salary,categories,Bonus
0,James Smith,29,1,3170000,Entry-Level,614299.6
1,Maria Garcia,37,8,4339738,Mid-Level,867947.6
2,Robert Johnson,28,6,4476605,Mid-Level,895321.0
3,Maria Rodriguez,27,5,4101196,Mid-Level,820239.2
4,David Smith,24,1,2824905,Entry-Level,564981.0
5,Mary Hernandez,35,4,4007157,Mid-Level,801431.4
6,Michael Williams,60,2,3668185,Mid-Level,733637.0
7,James Brown,34,12,5721024,Senior Management,1144204.8
8,Patricia Martinez,48,8,4760797,Senior Management,952159.4
9,Jennifer Miller,59,18,6233798,Executive,1246759.6
10,Linda Davis,32,7,4405142,Mid-Level,881028.4
11,Barbara Wilson,39,5,3820241,Mid-Level,764048.2
12,Elizabeth Moore,43,4,3446077,Entry-Level,689215.4
13,Richard Taylor,46,4,3808123,Mid-Level,761624.6
14,Thomas Anderson,44,20,6999639,Executive,1399927.8
15,Joseph Thomas,24,3,3737241,Mid-Level,747448.2
16,Charles Jackson,56,8,4664683,Senior Management,932936.6
17,Christopher White,27,5,3926149,Mid-Level,785229.8
18,Daniel Harris,45,19,6693950,Executive,1338790.0
19,Matthew Martin,26,1,3007339,Entry-Level,601467.8
20,Anthony Thompson,40,3,3429062,Entry-Level,685812.4
21,Donald Young,28,4,3697982,Mid-Level,739596.4
22,Mark King,51,21,7343591,Executive,1468718.2
23,Paul Wright,32,6,4218060,Mid-Level,843612.0
24,Steven Lopez,35,11,5135542,Senior Management,1027108.4
25,Andrew Scott,26,5,3760149,Mid-Level,752029.8
26,Kenneth Green,56,16,6032191,Executive,1206438.2
27,Joshua Adams,51,13,5554526,Senior Management,1110905.2
28,Kevin Baker,57,15,6043479,Executive,1208695.8
29,Brian Gonzalez,25,2,2948575,Entry-Level,589715.0
30,Rishab,26,1,9500000,Entry-level,8800000.0

In [34]:
# deleted row
df.drop(df[df.Employee_Name == 'Michael Williams'].index)

,Employee_Name,Age,Experience,Min Salary,categories,Bonus
0,James Smith,29,1,3170000,Entry-Level,614299.6
1,Maria Garcia,37,8,4339738,Mid-Level,867947.6
2,Robert Johnson,28,6,4476605,Mid-Level,895321.0
3,Maria Rodriguez,27,5,4101196,Mid-Level,820239.2
4,David Smith,24,1,2824905,Entry-Level,564981.0
5,Mary Hernandez,35,4,4007157,Mid-Level,801431.4
7,James Brown,34,12,5721024,Senior Management,1144204.8
8,Patricia Martinez,48,8,4760797,Senior Management,952159.4
9,Jennifer Miller,59,18,6233798,Executive,1246759.6
10,Linda Davis,32,7,4405142,Mid-Level,881028.4
11,Barbara Wilson,39,5,3820241,Mid-Level,764048.2
12,Elizabeth Moore,43,4,3446077,Entry-Level,689215.4
13,Richard Taylor,46,4,3808123,Mid-Level,761624.6
14,Thomas Anderson,44,20,6999639,Executive,1399927.8
15,Joseph Thomas,24,3,3737241,Mid-Level,747448.2
16,Charles Jackson,56,8,4664683,Senior Management,932936.6
17,Christopher White,27,5,3926149,Mid-Level,785229.8
18,Daniel Harris,45,19,6693950,Executive,1338790.0
19,Matthew Martin,26,1,3007339,Entry-Level,601467.8
20,Anthony Thompson,40,3,3429062,Entry-Level,685812.4
21,Donald Young,28,4,3697982,Mid-Level,739596.4
22,Mark King,51,21,7343591,Executive,1468718.2
23,Paul Wright,32,6,4218060,Mid-Level,843612.0
24,Steven Lopez,35,11,5135542,Senior Management,1027108.4
25,Andrew Scott,26,5,3760149,Mid-Level,752029.8
26,Kenneth Green,56,16,6032191,Executive,1206438.2
27,Joshua Adams,51,13,5554526,Senior Management,1110905.2
28,Kevin Baker,57,15,6043479,Executive,1208695.8
29,Brian Gonzalez,25,2,2948575,Entry-Level,589715.0
30,Rishab,26,1,9500000,Entry-level,8800000.0

In [35]:
df.drop('Bonus',axis= 1, inplace = True,errors='ignore') # delete of columns
df

        Employee_Name  Age  Experience  Min Salary         categories
0         James Smith   29           1     3170000        Entry-Level
1        Maria Garcia   37           8     4339738          Mid-Level
2      Robert Johnson   28           6     4476605          Mid-Level
3     Maria Rodriguez   27           5     4101196          Mid-Level
4         David Smith   24           1     2824905        Entry-Level
5      Mary Hernandez   35           4     4007157          Mid-Level
6    Michael Williams   60           2     3668185          Mid-Level
7         James Brown   34          12     5721024  Senior Management
8   Patricia Martinez   48           8     4760797  Senior Management
9     Jennifer Miller   59          18     6233798          Executive
10        Linda Davis   32           7     4405142          Mid-Level
11     Barbara Wilson   39           5     3820241          Mid-Level
12    Elizabeth Moore   43           4     3446077        Entry-Level
13     Richard Taylor   46           4     3808123          Mid-Level
14    Thomas Anderson   44          20     6999639          Executive
15      Joseph Thomas   24           3     3737241          Mid-Level
16    Charles Jackson   56           8     4664683  Senior Management
17  Christopher White   27           5     3926149          Mid-Level
18      Daniel Harris   45          19     6693950          Executive
19     Matthew Martin   26           1     3007339        Entry-Level
20   Anthony Thompson   40           3     3429062        Entry-Level
21       Donald Young   28           4     3697982          Mid-Level
22          Mark King   51          21     7343591          Executive
23        Paul Wright   32           6     4218060          Mid-Level
24       Steven Lopez   35          11     5135542  Senior Management
25       Andrew Scott   26           5     3760149          Mid-Level
26      Kenneth Green   56          16     6032191          Executive
27       Joshua Adams   51          13     5554526  Senior Management
28        Kevin Baker   57          15     6043479          Executive
29     Brian Gonzalez   25           2     2948575        Entry-Level
30             Rishab   26           1     9500000        Entry-level

In [36]:
df.drop(['Bonus','categories'],axis=1,errors = 'ignore') # deleting multiple values

        Employee_Name  Age  Experience  Min Salary
0         James Smith   29           1     3170000
1        Maria Garcia   37           8     4339738
2      Robert Johnson   28           6     4476605
3     Maria Rodriguez   27           5     4101196
4         David Smith   24           1     2824905
5      Mary Hernandez   35           4     4007157
6    Michael Williams   60           2     3668185
7         James Brown   34          12     5721024
8   Patricia Martinez   48           8     4760797
9     Jennifer Miller   59          18     6233798
10        Linda Davis   32           7     4405142
11     Barbara Wilson   39           5     3820241
12    Elizabeth Moore   43           4     3446077
13     Richard Taylor   46           4     3808123
14    Thomas Anderson   44          20     6999639
15      Joseph Thomas   24           3     3737241
16    Charles Jackson   56           8     4664683
17  Christopher White   27           5     3926149
18      Daniel Harris   45          19     6693950
19     Matthew Martin   26           1     3007339
20   Anthony Thompson   40           3     3429062
21       Donald Young   28           4     3697982
22          Mark King   51          21     7343591
23        Paul Wright   32           6     4218060
24       Steven Lopez   35          11     5135542
25       Andrew Scott   26           5     3760149
26      Kenneth Green   56          16     6032191
27       Joshua Adams   51          13     5554526
28        Kevin Baker   57          15     6043479
29     Brian Gonzalez   25           2     2948575
30             Rishab   26           1     9500000

In [37]:
df.sort_values('Min Salary')

        Employee_Name  Age  Experience  Min Salary         categories
4         David Smith   24           1     2824905        Entry-Level
29     Brian Gonzalez   25           2     2948575        Entry-Level
19     Matthew Martin   26           1     3007339        Entry-Level
0         James Smith   29           1     3170000        Entry-Level
20   Anthony Thompson   40           3     3429062        Entry-Level
12    Elizabeth Moore   43           4     3446077        Entry-Level
6    Michael Williams   60           2     3668185          Mid-Level
21       Donald Young   28           4     3697982          Mid-Level
15      Joseph Thomas   24           3     3737241          Mid-Level
25       Andrew Scott   26           5     3760149          Mid-Level
13     Richard Taylor   46           4     3808123          Mid-Level
11     Barbara Wilson   39           5     3820241          Mid-Level
17  Christopher White   27           5     3926149          Mid-Level
5      Mary Hernandez   35           4     4007157          Mid-Level
3     Maria Rodriguez   27           5     4101196          Mid-Level
23        Paul Wright   32           6     4218060          Mid-Level
1        Maria Garcia   37           8     4339738          Mid-Level
10        Linda Davis   32           7     4405142          Mid-Level
2      Robert Johnson   28           6     4476605          Mid-Level
16    Charles Jackson   56           8     4664683  Senior Management
8   Patricia Martinez   48           8     4760797  Senior Management
24       Steven Lopez   35          11     5135542  Senior Management
27       Joshua Adams   51          13     5554526  Senior Management
7         James Brown   34          12     5721024  Senior Management
26      Kenneth Green   56          16     6032191          Executive
28        Kevin Baker   57          15     6043479          Executive
9     Jennifer Miller   59          18     6233798          Executive
18      Daniel Harris   45          19     6693950          Executive
14    Thomas Anderson   44          20     6999639          Executive
22          Mark King   51          21     7343591          Executive
30             Rishab   26           1     9500000        Entry-level

In [38]:
df.sort_values('Min Salary', ascending = False)

        Employee_Name  Age  Experience  Min Salary         categories
30             Rishab   26           1     9500000        Entry-level
22          Mark King   51          21     7343591          Executive
14    Thomas Anderson   44          20     6999639          Executive
18      Daniel Harris   45          19     6693950          Executive
9     Jennifer Miller   59          18     6233798          Executive
28        Kevin Baker   57          15     6043479          Executive
26      Kenneth Green   56          16     6032191          Executive
7         James Brown   34          12     5721024  Senior Management
27       Joshua Adams   51          13     5554526  Senior Management
24       Steven Lopez   35          11     5135542  Senior Management
8   Patricia Martinez   48           8     4760797  Senior Management
16    Charles Jackson   56           8     4664683  Senior Management
2      Robert Johnson   28           6     4476605          Mid-Level
10        Linda Davis   32           7     4405142          Mid-Level
1        Maria Garcia   37           8     4339738          Mid-Level
23        Paul Wright   32           6     4218060          Mid-Level
3     Maria Rodriguez   27           5     4101196          Mid-Level
5      Mary Hernandez   35           4     4007157          Mid-Level
17  Christopher White   27           5     3926149          Mid-Level
11     Barbara Wilson   39           5     3820241          Mid-Level
13     Richard Taylor   46           4     3808123          Mid-Level
25       Andrew Scott   26           5     3760149          Mid-Level
15      Joseph Thomas   24           3     3737241          Mid-Level
21       Donald Young   28           4     3697982          Mid-Level
6    Michael Williams   60           2     3668185          Mid-Level
12    Elizabeth Moore   43           4     3446077        Entry-Level
20   Anthony Thompson   40           3     3429062        Entry-Level
0         James Smith   29           1     3170000        Entry-Level
19     Matthew Martin   26           1     3007339        Entry-Level
29     Brian Gonzalez   25           2     2948575        Entry-Level
4         David Smith   24           1     2824905        Entry-Level

In [39]:
import pandas as pd
import io
data = """Madhav,16,90000,CEO
Vishakha,17,70000,HR
Lalita,18,50000,CTO
Rishabh,19,30000,DA"""

columns = ['Name','Age','Salary','Team']
df = pd.read_csv(io.StringIO(data),names = columns)
df

       Name  Age  Salary Team
0    Madhav   16   90000  CEO
1  Vishakha   17   70000   HR
2    Lalita   18   50000  CTO
3   Rishabh   19   30000   DA

In [40]:
# Working with date value

df['DOJ']= ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']
df

       Name  Age  Salary Team         DOJ
0    Madhav   16   90000  CEO  2024-01-01
1  Vishakha   17   70000   HR  2024-01-15
2    Lalita   18   50000  CTO  2024-03-28
3   Rishabh   19   30000   DA  2024-03-03

In [41]:
df['DOJ'].dtype

In [42]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [43]:
df['DOJ'].dtype

dtype('<M8[us]')

In [44]:
df.drop('DOJ', axis = 1 ,inplace = True, errors = 'ignore')

In [45]:
df

       Name  Age  Salary Team
0    Madhav   16   90000  CEO
1  Vishakha   17   70000   HR
2    Lalita   18   50000  CTO
3   Rishabh   19   30000   DA

In [46]:
df['DOJ']= ["01-01-2024", "01-15-2024", "28-03-2024", "03-03-2024"]

In [47]:
df

       Name  Age  Salary Team         DOJ
0    Madhav   16   90000  CEO  01-01-2024
1  Vishakha   17   70000   HR  01-15-2024
2    Lalita   18   50000  CTO  28-03-2024
3   Rishabh   19   30000   DA  03-03-2024

In [48]:
df['DOJ'].dtype

In [49]:
 # 'mixed' tells Pandas to figure out each row's format on its own
df['DOJ'] = pd.to_datetime(df['DOJ'], dayfirst=True, format='mixed', errors='coerce')

In [50]:
df['DOJ'].dtype

dtype('<M8[us]')

In [51]:
df

       Name  Age  Salary Team        DOJ
0    Madhav   16   90000  CEO 2024-01-01
1  Vishakha   17   70000   HR 2024-01-15
2    Lalita   18   50000  CTO 2024-03-28
3   Rishabh   19   30000   DA 2024-03-03

In [52]:
# extract year
df['DOJ'].dt.year

0    2024
1    2024
2    2024
3    2024
Name: DOJ, dtype: int32

In [53]:
df["DOJ"].dt.month

0    1
1    1
2    3
3    3
Name: DOJ, dtype: int32

In [54]:
df["DOJ"].dt.day

0     1
1    15
2    28
3     3
Name: DOJ, dtype: int32

In [55]:
df["DOJ"].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: str

In [56]:
df["DOJ"].dt.month_name()

0    January
1    January
2      March
3      March
Name: DOJ, dtype: str

In [57]:
df['Month'] =df['DOJ'].dt.month_name()

In [58]:
df

       Name  Age  Salary Team        DOJ    Month
0    Madhav   16   90000  CEO 2024-01-01  January
1  Vishakha   17   70000   HR 2024-01-15  January
2    Lalita   18   50000  CTO 2024-03-28    March
3   Rishabh   19   30000   DA 2024-03-03    March

In [59]:
df["DOJ"]+= pd.Timedelta(days=90)
df

       Name  Age  Salary Team        DOJ    Month
0    Madhav   16   90000  CEO 2024-03-31  January
1  Vishakha   17   70000   HR 2024-04-14  January
2    Lalita   18   50000  CTO 2024-06-26    March
3   Rishabh   19   30000   DA 2024-06-01    March

In [61]:
# Handling missing value

In [62]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [64]:
import numpy as np

In [66]:
df.loc[df.Name== 'Madhav','Salary'] = np.nan 
df

       Name  Age   Salary Team        DOJ    Month
0    Madhav   16      NaN  CEO 2024-03-31  January
1  Vishakha   17  70000.0   HR 2024-04-14  January
2    Lalita   18  50000.0  CTO 2024-06-26    March
3   Rishabh   19  30000.0   DA 2024-06-01    March

In [67]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False    True  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [68]:
df.isnull().sum()

Name      0
Age       0
Salary    1
Team      0
DOJ       0
Month     0
dtype: int64

In [71]:
df.fillna(0)

       Name  Age   Salary Team        DOJ    Month
0    Madhav   16      0.0  CEO 2024-03-31  January
1  Vishakha   17  70000.0   HR 2024-04-14  January
2    Lalita   18  50000.0  CTO 2024-06-26    March
3   Rishabh   19  30000.0   DA 2024-06-01    March

In [73]:
# Aggregation and  group by

In [74]:
df['Month'].value_counts()

Month
January    2
March      2
Name: count, dtype: int64

In [83]:
df[df['Month'] =='January'].value_counts()

Name      Age  Salary   Team  DOJ         Month
Vishakha  17   70000.0  HR    2024-04-14  January    1
Name: count, dtype: int64

In [84]:
df.groupby('Month')['Salary'].sum()

Month
January    70000.0
March      80000.0
Name: Salary, dtype: float64

In [85]:
df.groupby('Month')['Salary'].mean()

Month
January    70000.0
March      40000.0
Name: Salary, dtype: float64

In [86]:
df.groupby('Month').agg({'Salary': 'mean', 'Name': 'count'})

          Salary  Name
Month
January  70000.0     2
March    40000.0     2

In [87]:
# Concatenate and Merge DataFrame(JOINS)

In [97]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [98]:
df2 = pd.DataFrame({'ID':[1,2,3,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   3     77
3   4     79

In [100]:
pd.concat([df1,df2],axis =0 ) # addition of rows vertically

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   3  NaN   77.0
3   4  NaN   79.0

In [101]:
pd.concat([df1,df2],axis =1 )  # addition of rows horizontally

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   3     77
3  NaN  NaN   4     79

In [102]:
#  merge = join

In [103]:
pd.merge(df1,df2, how = 'inner' , on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77

In [104]:
pd.merge(df1,df2, how = 'left' , on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77

In [105]:
pd.merge(df1,df2, how = 'inner' , left_on = 'ID',right_on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77

In [107]:
# AI and ChatGPT

In [108]:
# For the given dataframe, write a pandas script to filter employees whose 
# joining date is in the month of January and whose salary is greater 
# than 70,000
# Data Table:
#   Name,Age,Salary,Team,DOJ,Month
# Madhav,16,90000,CEO,2024-01-01,1
# Vishakha,17,70000,HR,2024-01-15,1
# Lalita,18,50000,CTO,2024-03-28,3

In [109]:
data = data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita'],
    'Age': [16, 17, 18],
    'Salary': [90000, 70000, 50000],
    'Team': ['CEO', 'HR', 'CTO'],
    'DOJ': ['2024-01-01', '2024-01-15', '2024-03-28'],
    'Month': [1, 1, 3]
}

df = pd.DataFrame(data)
df

       Name  Age  Salary Team         DOJ  Month
0    Madhav   16   90000  CEO  2024-01-01      1
1  Vishakha   17   70000   HR  2024-01-15      1
2    Lalita   18   50000  CTO  2024-03-28      3

In [114]:
 df[(df['Month'] == 1) & (df['Salary'] >= 70000)]

       Name  Age  Salary Team         DOJ  Month
0    Madhav   16   90000  CEO  2024-01-01      1
1  Vishakha   17   70000   HR  2024-01-15      1

In [115]:
df.query('Month == 1 and Salary > 70000')

     Name  Age  Salary Team         DOJ  Month
0  Madhav   16   90000  CEO  2024-01-01      1

In [116]:
# Create a DataFrame to practise pivot table in pandas (using AI prompt)

In [117]:
import pandas as pd

In [125]:
data =data = {
    'Name': ['Aarav', 'Aarav', 'Ishani', 'Ishani', 'Kabir', 'Kabir'],
    'Subject': ['Maths', 'Science', 'Maths', 'Science', 'Maths', 'Science'],
    'Marks': [85, 78, 94, 88, 72, 81]
}

df = pd.DataFrame(data)
df

     Name  Subject  Marks
0   Aarav    Maths     85
1   Aarav  Science     78
2  Ishani    Maths     94
3  Ishani  Science     88
4   Kabir    Maths     72
5   Kabir  Science     81

In [128]:
pivot_Table = pd.pivot_table(df,values = 'Marks',index = 'Name',columns = 'Subject',aggfunc = 'mean')
pivot_Table

Subject  Maths  Science
Name
Aarav     85.0     78.0
Ishani    94.0     88.0
Kabir     72.0     81.0